version: "3"
services:
    frontend:
        container_name: frontend
        build: 
            context: .
        image: frontend
        ports:
            - "8080:80"
networks:
    default:
       external:
          name: allnetwork
