version: "3"
services:
    frontend:
        container_name: frontend
        build: 
            context: .
        image: frontend
        ports:
            - "80:80"
    proxy:
        build: /Caddyfile
        ports: 
            - 3333:3333 
    api:
        build: .

networks:
    default:
       external:
          name: allnetwork