version: "3"
services:
    frontend:
        container_name: frontend
        build: 
            context: .
        image: frontend

networks:
    default:
       external:
          name: allnetwork